services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-langchain}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-langchain}
      POSTGRES_DB: ${POSTGRES_DB:-langchain}
    ports:
      - "6024:5432"
    restart: unless-stopped
